config/routes.rb
Sampleapp::Application.routes.draw do
  

  get "attachments/show"

  get "attachments/create"
  post "attachments/create"

resources :users

resources :sessions, :only => [:new, :create, :destroy]
match 'attachments/:id/file',:to=>'attachments#me'
match '/users/:id/course1', :to=>'users#course1'
match '/users/:id/course2', :to=>'users#course2'
match '/users/:id/course3', :to=>'users#course3'
match '/users/:id/course4', :to=>'users#course4'
match '/users/:id/course5', :to=>'users#course5'
match '/users/:id/course6', :to=>'users#course6'
match '/users/:id/course7', :to=>'users#course7'
  match '/developers', :to=>'pages#developers'

  match '/contact', :to=>'pages#contact'
match '/about', :to=>'pages#about'
match '/help', :to=>'pages#help'
match'/signup',:to=>'users#new'

match '/signin', :to => 'sessions#new'
match '/signout', :to => 'sessions#destroy'
root :to=>'pages#home'

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
belongs_to:user
attr_accessible :course   
 def uploaded_file=(incoming_file)
        self.filename = incoming_file.original_filename
        self.content_type = incoming_file.content_type
        self.data = incoming_file.read
        
    end
    
    
    def filename=(new_filename)
        write_attribute("filename", sanitize_filename(new_filename))
    end

    private
    def sanitize_filename(filename)
        #get only the filename, not the whole path (from IE)
        just_filename = File.basename(filename)
        #replace all non-alphanumeric, underscore or periods with underscores
        just_filename.gsub(/[^\w\.\-]/, '_')
    end
def sanitize_course(course)
        #get only the filename, not the whole path (from IE)
        just_course = File.basename(course)
        #replace all non-alphanumeric, underscore or periods with underscores
        just_course.gsub(/[^\w\.\-]/, '_')
    end


end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
has_many :attachments
   attr_accessor :password
attr_accessible :name, :email, :password, :password_confirmation,:rollno,:department,:cn1,
:cn2,:cn3,:cn4,:cn5,:cn6,:cn7, :image, :remote_image_url

mount_uploader :image, ImageUploader






  email_regex = /\A[\w+\-.]+@iitk.ac.in/i
validates :name, :presence => true,
:length => { :maximum => 50 }
validates :email, :presence => true,
:format => { :with => email_regex ,:message=>"id of IITK should be used "},
:uniqueness => { :case_sensitive => false }
validates :password, :presence => true,
:confirmation => true,
:length => { :within => 6..40 }
before_save :encrypt_password

def has_password?(submitted_password)
encrypted_password == encrypt(submitted_password)
end
def self.authenticate(email, submitted_password)
user = find_by_email(email)
return nil if user.nil?
return user if user.has_password?(submitted_password)
end
def self.authenticate_with_salt(id, cookie_salt)
user = find_by_id(id)
(user && user.salt == cookie_salt) ? user : nil
end

private
def encrypt_password
self.salt = make_salt if new_record?
self.encrypted_password = encrypt(password)
end
def encrypt(string)
secure_hash("#{salt}--#{string}")
end
def make_salt
secure_hash("#{Time.now.utc}--#{password}")
end
def secure_hash(string)
Digest::SHA2.hexdigest(string)
end
end
   

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery


include SessionsHelper


end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController

def new
 @attachment=Attachment.new
end    
def me 
a = Attachment.find(params[:id])
send_data   a.data, :filename => a.filename, :type => a.content_type
    end

def show
        #@attachment = Attachment.find(params[:id])
       #send_data  @attachment.id, @attachment.data, :filename => @attachment.filename, :type => @attachment.content_type
    end

    def create      
        return if params[:attachment].blank?

        @attachment = Attachment.new
        @attachment.course=params[:attachment][:course]
        @attachment.uploaded_file = params[:a]

        if @attachment.save
            flash[:notice] = "Thank you for your submission..."
            redirect_to :action => "show"
        else
            flash[:error] = "There was a problem submitting your attachment."
            render :action => :new
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
 


 def home
@title="Home"
  end
def about
@title="About"
end
  def contact
@title="Contact"  
end
def help
@title="Help"
end
def contact
@title="Contact"  
end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
def new
@title = "Sign in"
end

def create
user = User.authenticate(params[:session][:email],
params[:session][:password])
if user.nil?
flash.now[:error] = "Invalid email/password combination."
@title = "Sign in"
render 'new'
else
sign_in user
redirect_back_or user
end
end

def destroy
sign_out
redirect_to root_path
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_filter :authenticate, :only => [ :index,:edit,:update]
before_filter :correct_user, :only => [:edit, :update]
before_filter :admin_user, :only => :destroy


def course1
@user=User.find(params[:id])
end

def course2
@user=User.find(params[:id])
end
def course3
@user=User.find(params[:id])
end
def course4
@user=User.find(params[:id])
end
def course5
@user=User.find(params[:id])
end
def course6
@user=User.find(params[:id])
end

def course7
@user=User.find(params[:id])
end

def index
@title = "All users"
@users = User.paginate(:page => params[:page])
end
def show
@user = User.find(params[:id])

@title = @user.name
end
def new
@user = User.new
@title = "Sign up"
end
def create
@user = User.new(params[:user])
if @user.save
sign_in @user
flash[:success] = "Welcome to lecpool!"
redirect_to @user
else
@title = "Sign up"
render 'new'
end
end
def edit
@user = User.find(params[:id])
@title = "Edit user"
end
def update
@user = User.find(params[:id])
if @user.update_attributes(params[:user])
flash[:success] = "Profile updated."
redirect_to @user
else
@title = "Edit user"
render 'edit'
end
end
def destroy
User.find(params[:id]).destroy
flash[:success] = "User destroyed."
redirect_to users_path
end

private
def authenticate
deny_access unless signed_in?
end

def correct_user
@user = User.find(params[:id])
redirect_to(root_path) unless current_user?(@user)
end

def admin_user
redirect_to(root_path) unless current_user.admin?
end
end

app/helpers/application_helper.rb
module ApplicationHelper



def logo
image_tag("logo.png", :alt => "Sample App", :class => "round")
end

end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper


def sign_in(user)
cookies.permanent.signed[:remember_token] = [user.id, user.salt]
current_user = user
end


def current_user=(user)
@current_user = user
end


def current_user
@current_user ||= user_from_remember_token
end
def destroy
sign_out
redirect_to root_path
end

def signed_in?
!current_user.nil?
end




def sign_out
cookies.delete(:remember_token)
current_user = nil
end


private
def user_from_remember_token
User.authenticate_with_salt(*remember_token)
end
def remember_token
cookies.signed[:remember_token] || [nil, nil]
end


def current_user?(user)
user == current_user
end
def deny_access
redirect_to signin_path, :notice => "Please sign in to access this page."
end



def store_location
session[:return_to] = request.fullpath
end
def redirect_back_or(default)
redirect_to(session[:return_to] || default)
clear_return_to
end
def clear_return_to
session[:return_to] = nil
end







end

app/helpers/users_helper.rb
module UsersHelper


def gravatar_for(user, options = { :size => 50 })
gravatar_image_tag(user.email.downcase, :alt => user.name,
:class => 'gravatar',
:gravatar => options)
end







end

app/views/attachments/create.html.erb
<% form_tag 'create', :multipart => true do %>
Course:<br />

<input id="attachment_course" name="attachment[course]" type="text" /><br />


    <%= file_field_tag 'a' %>
    <%= submit_tag "Send Attachment" %>

<% end %>

app/views/attachments/new.html.erb
<% form_tag 'create', :multipart => true do %>
    <%= file_field_tag 'attachment' %>
    <%= submit_tag "Send Attachment" %>
<% end %>

app/views/attachments/show.html.erb
<h3>Files:</h3>
<%Attachment.all.each do |t|%>
<a href ="/attachments/<%=t.id%>/file"><%=t.filename%></a> Posted by: <%=t.user%> <br />
<%end%>

app/views/layouts/_error_messages.html.erb
<%if @user.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(@user.errors.count, "error") %>
prohibited this user from being saved:</h2>
<p>There were problems with the following fields:</p>
<ul>
<% @user.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
<nav class="round">
<ul>
<li><%= link_to "About", about_path %></li>
<li><%= link_to "Contact", contact_path %></li>
<li><%= link_to "Developers", developers_path %></li>

</ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<header>


<%= link_to logo, root_path %>
<nav class="round">

<nav class="round">
<ul>
<li><%= link_to "Home", root_path %></li>


<% if signed_in? %>
<li><%= link_to "Users", users_path %></li>
<li><%= link_to "Profile", current_user %></li>

<li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
<% end %>

<% if signed_in? %>
<li><%= link_to "Upload", attachments_create_path  %></li>


<li><%= link_to "Sign out", signout_path, :method => :delete %></li>
<% else %>
<li><%= link_to "Sign in", signin_path %></li>
<% end %>




</ul>
</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>


 
<script language="javaScript">
var pos=0;
var str="Lec Pool-Platform for all IIT-k Lectures | <%=@title %>  ";
// npos is used for forward scrolling
var npos=str.length;
// Normal upDate(). Other options upDateFW() and upDateWD()
setInterval("upDate()",300);
 
// Normal Scroll
function upDate()
{
  // Reset the title starting at pos
  document.title=str.substring(pos,str.length)+str.substring(0,pos);
  if(pos < str.length) pos++;
  else pos = 0;
}
 
// Scroll forward
function upDateFW()
{
  // Reset the title starting at pos
  document.title=str.substring(npos,str.length)+str.substring(0,npos);
  if(npos > 0) npos--;
  else npos = str.length;
}
 
// Scroll With Delay
var delay = 20;
function upDateWD()
{
  if(pos < str.length) {
    document.title=str.substring(pos,str.length)+str.substring(0,pos);
  }  else {
    if(pos > str.length+delay) {
      pos = 0;
    }
  }
  pos++;
}
</script>













<title id="title" class="title"> Lec Pool-Platform for all IIT-k Lectures | <%=@title %></title>
<%= csrf_meta_tag %>
<%=render 'layouts/stylesheets'%>
</head>
<body>
<div class="container">
<%=render 'layouts/header'%>

<section class="round">






<% flash.each do |key, value| %>
<div class="flash <%= key %>"><%= value %></div>
<% end %>








<%= yield %>
</section>
<%=render 'layouts/footer'%>

</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>
<a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
is a project to make a book and screencasts to teach web development
with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
is the sample application for the tutorial.
</p>
With these views

app/views/pages/contact.html.erb
<h1>About Us</h1>
<p>
<a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
is a project to make a book and screencasts to teach web development
with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
is the sample application for the tutorial.
</p>

app/views/pages/help.html.erb
<html>
<head>
<title>
Welcome</title>
</head>
<body>
Hi
</body>
</html>

app/views/pages/home.html.erb
<h1>Lec Pool</h1>
<p>
This is the home page for the
Lec Pool application.
</p><%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(@user.errors.count, "error") %>
prohibited this user from being saved:</h2>
<p>There were problems with the following fields:</p>
<ul>
<% @user.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

app/views/shared/_user_info.html.erb
<div class="user_info">
<a href="<%= user_path(current_user) %>">
<%= gravatar_for current_user, :size => 30 %>
<span class="user_name">
<%= current_user.name %>
</span>
<span class="microposts">
<%= pluralize(current_user.microposts.count, "micropost") %>
</span>
</a>
</div>

app/views/users/_user.html.erb
<li>
<%= image_tag user.image_url(:thumb) if user.image? %>
<%= link_to user.name, user %>
<% if current_user.admin? %>
| <%= link_to "delete", user, :method => :delete, :confirm => "You sure?",
:title => "Delete #{user.name}" %>
<% end %>
</li>

app/views/users/course1.html.erb
<h1><strong><%=@user.cn1%></strong></h1>

<%Attachment.all.each do |t|%>
<%if t.course==@user.cn1%>
<a href ="/attachments/<%=t.id%>/file"><%=t.filename%></a> Posted by: <%=t.user%> <br />
<%end%>
<%end%>

app/views/users/course2.html.erb
<h1 size="10"><strong><%=@user.cn2%></strong></h1>
<%Attachment.all.each do |t|%>
<%if t.course==@user.cn2%>
<a href ="/attachments/<%=t.id%>/file"><%=t.filename%></a> Posted by: <%=t.user%> <br />
<%end%>
<%end%>

app/views/users/course3.html.erb
<h1 size="10"><strong><%=@user.cn3%></strong></h1>
<%Attachment.all.each do |t|%>
<%if t.course==@user.cn3%>
<a href ="/attachments/<%=t.id%>/file"><%=t.filename%></a> Posted by: <%=t.user%> <br />
<%end%>
<%end%>

app/views/users/course4.html.erb
<h1 size="10"><strong><%=@user.cn4%></strong></h1>
<%Attachment.all.each do |t|%>
<%if t.course==@user.cn4%>
<a href ="/attachments/<%=t.id%>/file"><%=t.filename%></a> Posted by: <%=t.user%> <br />
<%end%>
<%end%>

app/views/users/course5.html.erb
<h1 size="10"><strong><%=@user.cn5%></strong></h1>
<%Attachment.all.each do |t|%>
<%if t.course==@user.cn5%>
<a href ="/attachments/<%=t.id%>/file"><%=t.filename%></a> Posted by: <%=t.user%> <br />
<%end%>
<%end%>

app/views/users/course6.html.erb
<h1 size="10"><strong><%=@user.cn6%></strong></h1>
<%Attachment.all.each do |t|%>
<%if t.course==@user.cn6%>
<a href ="/attachments/<%=t.id%>/file"><%=t.filename%></a> Posted by: <%=t.user%> <br />
<%end%>
<%end%>

app/views/users/course7.html.erb
<h1 size="10"><strong><%=@user.cn7%></strong></h1>
<%Attachment.all.each do |t|%>
<%if t.course==@user.cn7%>
<a href ="/attachments/<%=t.id%>/file"><%=t.filename%></a> Posted by: <%=t.user%> <br />
<%end%>
<%end%>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>
<%= form_for(@user) do |f| %>
<%= render 'shared/error_messages', :object => f.object %>
<div class="field">
<%= f.label :name %><br />
<%= f.text_field :name %>
</div>
<div class="field">
<%= f.label :email %><br />
<%= f.text_field :email %>
</div>
<div class="field">
<%= f.label :password %><br />
<%= f.password_field :password %>
</div>
<div class="field">
<%= f.label :password_confirmation, "Confirmation" %><br />
<%= f.password_field :password_confirmation %>
</div>
<div class="field">
<%= f.label :cn1, "Course No.1" %><br />
<%= f.text_field :cn1 %>
</div>
<div class="field">

<div class="field">
<%= f.label :cn2, "Course No.2" %><br />
<%= f.text_field :cn2 %>
</div>
<div class="field">
<%= f.label :cn3, "Course No.3" %><br />
<%= f.text_field :cn3 %>
</div>
<div class="field">
<%= f.label :cn4, "Course No.4" %><br />
<%= f.text_field :cn4 %>
</div>
<div class="field">
<%= f.label :cn5, "Course No.5" %><br />
<%= f.text_field :cn5 %>
</div>
<div class="field">
<%= f.label :cn6, "Course No.6" %><br />
<%= f.text_field :cn6 %>
</div>
<div class="field">
<%= f.label :cn7, "Course No.7" %><br />
<%= f.text_field :cn7 %>
</div>




<div class="actions">
<%= f.submit "Update" %>
</div>
<% end %>
<div>

</div>

app/views/users/index.html.erb
<h1>All users</h1>
<%= will_paginate %>
<ul class="users">
<% @users.each do |user| %>
<%= render user %>
<% end %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for @user, :html => {:multipart => true} do |f| %>


<%= render 'shared/error_messages', :object => f.object %>
<div class="field">
<%= f.label :name %><br />
<%= f.text_field :name %>
</div>
<div class="field">
<%= f.label :email %><br />
<%= f.text_field :email %>
</div>
<div class="field">
<%= f.label :password %><br />
<%= f.password_field :password %>
</div>
<div class="field">
<%= f.label :password_confirmation, "Confirmation" %><br />
<%= f.password_field :password_confirmation %>
</div>
<div class="field">
<label for="user_rollno">Roll No</label><br />
<input id="user_rollno" name="user[rollno]" size="10" />
</div>

<div class="field">
<label for="user_department">Department</label><br />

<select id="user_department" name="user[department]">
  <option value="Aerospace Engineering">Aerospace Engineering</option>
  <option value="Biological Sciences and Bioengineering">Biological Sciences and Bioengineering</option>
  <option value="Chemical Engineering">Chemical Engineering</option>
  <option value="Civil Engineering">Civil Engineering</option>

<option value="Computer Science and Engineering">Computer Science and Engineering</option>
  <option value="Electrical Engineering">Electrical Engineering</option>
  <option value="Industrial and Management Engineering">Chemical Engineering</option>
  <option value="Material Science and Engineering">Material Science and Engineering</option>
 <option value="Mechanical Engineering">Mechanical Engineering</option>
</div>

<div class="field">
    <%= f.file_field :image %></br>
</div>
<div class="field">
    <%= f.label :remote_image_url, "Or image URL" %><br />
    <%= f.text_field :remote_image_url %>
</div>



</select>
<div class="actions">
<%= f.submit "Sign up" %>
</div>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
<tr>






<td class="main">



<h1>
<%= image_tag @user.image_url(:thumb) if @user.image? %>

</h1>
</td>
<td class="sidebar" >
<strong> <font size="4"><b>Name: </strong> <%= @user.name %></font></b><br />

<strong><font size="4"><b>Roll No: </strong> <%= @user.rollno %></font></b><br />
<strong><font size="4"><b>Department: </strong> <%= @user.department %></font></b><br />

<strong><font size="4"><b>Courses: </strong> </font></b>

<a href="/users/<%=params[:id]%>/edit">To Add or Change a course click Here !</a><br />
<a href="/users/<%=params[:id]%>/course1"><%=@user.cn1%></a><br />
<a href="/users/<%=params[:id]%>/course2"><%=@user.cn2%></a><br />
<a href="/users/<%=params[:id]%>/course3"><%=@user.cn3%></a><br />
<a href="/users/<%=params[:id]%>/course4"><%=@user.cn4%></a><br />
<a href="/users/<%=params[:id]%>/course5"><%=@user.cn5%></a><br />
<a href="/users/<%=params[:id]%>/course6"><%=@user.cn6%></a><br />
<a href="/users/<%=params[:id]%>/course7"><%=@user.cn7%></a><br />






</td>
</tr>
</table>